import localFont from "next/font/local";
import "./globals.css";
import SocketContextProvider from "@/context/SocketContext";
import RegistrationContextProvider from "@/context/RegistrationContext";
import ResponsiveLayout from "@/components/ResponsiveLayout";
import OverallContextProvider from "@/context/OverallContext";
import ChatContextProvider from "@/context/ChatContext";
import CallContextProvider from "@/context/CallContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OverallContextProvider>
        <RegistrationContextProvider>
          <SocketContextProvider>
            <CallContextProvider>
            <ChatContextProvider>
            <ResponsiveLayout>
            {children}
            </ResponsiveLayout>
            </ChatContextProvider>
            </CallContextProvider>
          </SocketContextProvider>
        </RegistrationContextProvider>
        </OverallContextProvider>
      </body>
    </html>
  );
}
